# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/droplets/detector_ds  # dataset root dir
train: images/train
val: images/test
test:  # test images (optional)

# Classes
nc: 1  # number of classes
names: ['circle']  # class names